### ISSUE TITLE
Example on homepage does not work

### ISSUE THREAD

**Issue by Nic30** [cgoldberg/concurrencytest#3]
....
----------------------------------------------------------------------
Ran 4 tests in 2.003s

OK
Traceback (most recent call last):
  File "/home/nic30/Documents/workspace/hwtLib/hwtLib/tests/all.py", line 144, in <module>
    runner.run(concurrent_suite)
  File "/usr/lib/python3.5/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/lib/python3.5/dist-packages/unittest2/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/testtools/testsuite.py", line 82, in run
    tests = self.make_tests(self)
  File "/usr/local/lib/python3.5/dist-packages/concurrencytest.py", line 65, in do_fork
    process_suite = unittest.TestSuite(process_tests)
  File "/usr/lib/python3.5/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.5/unittest/suite.py", line 58, in addTests
    self.addTest(test)
  File "/usr/lib/python3.5/unittest/suite.py", line 47, in addTest
    raise TypeError("{} is not callable".format(repr(test)))
TypeError: None is not callable

**Comment by Nic30** [comment]
suite can not run twice

**Comment by cgoldberg** [comment]
it works in Python 2.x... just not Python 3.  I'll need to look into this when I have more time.

**Comment by Nic30** [comment]
maybe just create new instance of suite in example, it will be enough
