### ISSUE TITLE
Tests fail on python3.4

### ISSUE THREAD

**Issue by ecederstrand** [cgoldberg/concurrencytest#4]
In hunting down a different issue, I tried to run the test case on my Python version:

```bash
$ python3.4 my_virtualenv/lib/python3.4/site-packages/concurrencytest.py 
....
----------------------------------------------------------------------
Ran 4 tests in 2.003s

OK
Traceback (most recent call last):
  File "my_virtualenv/lib/python3.4/site-packages/concurrencytest.py", line 144, in <module>
    runner.run(concurrent_suite)
  File "/usr/lib/python3.4/unittest/runner.py", line 168, in run
    test(result)
  File "my_virtualenv/lib/python3.4/site-packages/unittest2/suite.py", line 87, in __call__
    return self.run(*args, **kwds)
  File "my_virtualenv/lib/python3.4/site-packages/testtools/testsuite.py", line 82, in run
    tests = self.make_tests(self)
  File "my_virtualenv/lib/python3.4/site-packages/concurrencytest.py", line 65, in do_fork
    process_suite = unittest.TestSuite(process_tests)
  File "/usr/lib/python3.4/unittest/suite.py", line 24, in __init__
    self.addTests(tests)
  File "/usr/lib/python3.4/unittest/suite.py", line 58, in addTests
    self.addTest(test)
  File "/usr/lib/python3.4/unittest/suite.py", line 47, in addTest
    raise TypeError("{} is not callable".format(repr(test)))
TypeError: None is not callable
```

**Comment by ecederstrand** [comment]
Sorry, duplicate of #3
